#!/bin/bash
#SBATCH --job-name=python        # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks-per-node=1      # total number of tasks per node
#SBATCH --cpus-per-task=1        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem=8G                 # memory
#SBATCH --time=00:10:00          # total run time limit (HH:MM:SS)

module load anaconda3/2025.12
conda activate cms

python example.py > example.out
